name: Build and Export Snap

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build on ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Snap
        uses: snapcore/action-build@v1
        with:
          path: .
          architectures: ${{ matrix.arch }}

      - name: Rename snap file
        run: mv *.snap python3-alt-${{ matrix.arch }}.snap

      - name: Upload snap artifact
        uses: actions/upload-artifact@v2
        with:
          name: python3-alt-${{ matrix.arch }}
          path: ./*.snap